CREATE TABLE IF NOT EXISTS bankers
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR(255) NOT NULL,
    cognome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(255) NOT NULL,
    cognome   VARCHAR(255) NOT NULL,
    id_banker INT,
    FOREIGN KEY (id_banker) REFERENCES bankers (id)
);

CREATE TABLE IF NOT EXISTS appointments
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data       DATE NOT NULL,
    esito      VARCHAR(255),
    polizza    VARCHAR(255),
    premio     INT,
    id_cliente INT,
    id_banker  INT,
    note       TEXT,
    FOREIGN KEY (id_cliente) REFERENCES clients (id),
    FOREIGN KEY (id_banker) REFERENCES bankers (id)
);

CREATE TABLE IF NOT EXISTS callbacks
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data       DATE,
    data_app   DATE NOT NULL,
    id_cliente INT,
    id_banker  INT,
    note       TEXT,
    FOREIGN KEY (id_cliente) REFERENCES clients (id),
    FOREIGN KEY (id_banker) REFERENCES bankers (id)
);

CREATE TABLE IF NOT EXISTS esiti
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    esito VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS polizze
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polizza VARCHAR(255)
);

INSERT INTO esiti (esito)
SELECT esito
FROM (SELECT 'Sottoscrizione' AS esito
      UNION ALL
      SELECT 'Rifiuto'
      UNION ALL
      SELECT 'Callback'
      UNION ALL
      SELECT 'Checkup'
      UNION ALL
      SELECT 'Assistenza'
      UNION ALL
      SELECT 'Primo Appuntamento') AS new_esiti
WHERE NOT EXISTS (SELECT 1 FROM esiti WHERE esiti.esito = new_esiti.esito);

INSERT INTO polizze (polizza)
SELECT 'Personal Life Serenity' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze)
UNION ALL
SELECT 'Capitale Persona Malattia Grave' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze)
UNION ALL
SELECT 'Capitale Casa e Famiglia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze)
UNION ALL
SELECT 'Capitale Autonomia' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze)
UNION ALL
SELECT 'Capitale Salute' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze)
UNION ALL
SELECT 'Key People' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze)
UNION ALL
SELECT '4Assistance' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM polizze);
